name: auto_size_text_pro
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 3.0.1
# authors:
#   - Kevin Kobori <kevinyujikobori@gmail.com>
#   - Filip Grzywok <f.grzywok@gmail.com>
homepage: https://fluttely.com
repository: https://github.com/Fluttely/auto_size_text_pro

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '>=1.11.1 <3.0.0'